# Generated by Django 6.0.3 on 2026-04-02 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone_number', models.CharField(help_text='Virtual tests can use any number format', max_length=20, verbose_name='WhatsApp Number')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('department', models.CharField(max_length=150, verbose_name='Department')),
                ('role', models.CharField(choices=[('STAFF', 'Staff/Employee'), ('PROFESSOR', 'Professor')], default='STAFF', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Holiday/Occasion Name')),
                ('date', models.DateField(blank=True, help_text='Use this for one-time holidays', null=True, verbose_name='Specific Date')),
                ('recurring_month', models.IntegerField(blank=True, help_text='1-12 for recurring yearly holidays (e.g., 12 for Christmas)', null=True)),
                ('recurring_day', models.IntegerField(blank=True, help_text='Day of the month for recurring holidays (e.g., 25)', null=True)),
                ('message_template', models.TextField(help_text="Use {name} to insert the employee's name.", verbose_name='Message Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(help_text='e.g., Birthday, Christmas, etc.', max_length=50)),
                ('platform', models.CharField(help_text='WhatsApp or Telegram', max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='core.employee')),
            ],
        ),
    ]
